### ISSUE TITLE
Venstar driver crash

### ISSUE THREAD

**Issue by gtfierro** [SoftwareDefinedBuildings/bw2-contrib#6]
```
[04/05 10:32:28] alpha::venstar > panic: runtime error: invalid memory address or nil pointer dereference
[04/05 10:32:28] alpha::venstar > [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x403c71]
[04/05 10:32:28] alpha::venstar > 
[04/05 10:32:28] alpha::venstar > goroutine 153 [running]:
[04/05 10:32:28] alpha::venstar > panic(0x97f300, 0xc42000c060)
[04/05 10:32:28] alpha::venstar >       /usr/local/go/src/runtime/panic.go:500 +0x1a1
[04/05 10:32:28] alpha::venstar > main.(*Driver).Scrape(0xc42019dc20)
[04/05 10:32:28] alpha::venstar >       /srv/go/src/github.com/SoftwareDefinedBuildings/bw2-contrib/driver/venstar/driver.go:145 +0xc1
[04/05 10:32:28] alpha::venstar > main.(*Driver).Start(0xc42019dc20)
[04/05 10:32:28] alpha::venstar >       /srv/go/src/github.com/SoftwareDefinedBuildings/bw2-contrib/driver/venstar/driver.go:58 +0x10c
[04/05 10:32:28] alpha::venstar > created by main.newThermostat
[04/05 10:32:28] alpha::venstar >       /srv/go/src/github.com/SoftwareDefinedBuildings/bw2-contrib/driver/venstar/driver.go:44 +0x1f9
```

The issue is likely that we read the contents of the GET request before we actually check for an error (see https://github.com/SoftwareDefinedBuildings/bw2-contrib/blob/master/driver/venstar/driver.go#L145)

**Comment by peterxu30** [comment]
Pushed an update to check error before reading contents.
